p8105-hw2-yw4662
================

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(haven)
library(readxl)
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(knitr)
```

## Problem 1

### 1. Clean the data in pols-month.csv

``` r
pols <- read_csv("./data/pols-month.csv") %>%
  clean_names() %>%
  
  # Split mon into year, month, day as integers
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>%
  
  # Replace month number with month name
  mutate(month = month.name[month],
         # Create president from indicator cols
         president = if_else(prez_gop == 1, "gop", "dem"),
         president = factor(president, levels = c("gop", "dem"))) %>%
  
  # Remove prez_dem, prez_gop, and day variables
  select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <fct>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

### 2. Clean the data in snp.csv

``` r
snp <- read_csv("./data/snp.csv") %>%
  clean_names() %>%
  
  # Parse the data
  mutate(date = mdy(date),
         year = year(date),
         mon_n = month(date)) %>%
  mutate(month = month.name[mon_n]) %>%
  select(-mon_n, -date) %>%
  
  # Make year & month leading columns
  relocate(year, month, .before = 1) %>%
  
  # Arrange according to year and month
  arrange(year, month(match(month, month.name)))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <dbl> <chr>     <dbl>
    ##  1  1969 January   103. 
    ##  2  1969 February   98.1
    ##  3  1969 March     102. 
    ##  4  1969 April     104. 
    ##  5  1969 May       103. 
    ##  6  1969 June       97.7
    ##  7  1969 July       91.8
    ##  8  1969 August     95.5
    ##  9  1969 September  93.1
    ## 10  1969 October    97.1
    ## # ℹ 777 more rows

### 3. Tidy the unemployment data

``` r
unemp <- read_csv("./data/unemployment.csv") %>%
  clean_names() %>%
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) %>%
  mutate(
    year = as.integer(year),
    month = str_to_title(month.name[match(month, tolower(month.abb))]) # matching
  ) %>%
  relocate(year, month, .before = 1) %>%
  arrange(year, match(month, month.name))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemp
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <int> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

### 4. Merge the datasets

``` r
mm <- factor(month.name, levels = month.name)

pols <- pols %>%
  mutate(
    year = as.integer(year),
    month = factor(month, levels = levels(mm))
  ) %>%
  arrange(year, month)

snp <- snp %>%
  mutate(
    year = as.integer(year),
    month = factor(month, levels = levels(mm))
  ) %>%
  arrange(year, month)

unemp <- unemp %>%
  mutate(
    year = as.integer(year),
    month = factor(month, levels = levels(mm))
  ) %>%
  arrange(year, month)

# Merging
merged <- pols %>%
  left_join(snp, by = c("year", "month")) %>%
  left_join(unemp, by = c("year", "month"))

merged
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <int> <fct>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <fct>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

### 5. Comment

The **pols** table contains monthly U.S. politicians counts and a
`president` indicator; it spans 1947 - 2015 with 822 rows. The **snp**
table adds monthly S&P returns, and the **unemp** table provides monthly
unemployment rates for 68 years.

After merging on `year` and `month`, the resulting dataset has 822 rows
× 11 columns; key variables include `year`, `month`, `president`,
`unemployment`, and the S&P return column from `close`.

## Problem 2

### Data cleaning

``` r
path <- "./data/202509 Trash Wheel Collection Data.xlsx"

# Mr. Trash Wheel
mr_trash <- read_excel(
  path,
  sheet = "Mr. Trash Wheel",   # specify the sheet
  range = cell_limits(c(2,1),c(NA,14)),   # omit non-data rows/columns
  na = c("NA", ".", "")   # treat these as missing
) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%   # keep only dumpster-specific rows
  mutate(
    date = as.Date(date),
    year = year(date),
    month_num = month(date),
    month = month.name[month_num],
    wheel = "Mr. Trash Wheel")
if (!"sports_balls" %in% names(mr_trash)) mr_trash$sports_balls <- NA_integer_
mr_trash
```

    ## # A tibble: 707 × 16
    ##    dumpster month  year date       weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <date>           <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16        4.31                 18
    ##  2        2 May    2014 2014-05-16        2.74                 13
    ##  3        3 May    2014 2014-05-16        3.45                 15
    ##  4        4 May    2014 2014-05-17        3.1                  15
    ##  5        5 May    2014 2014-05-17        4.06                 18
    ##  6        6 May    2014 2014-05-20        2.71                 13
    ##  7        7 May    2014 2014-05-21        1.91                  8
    ##  8        8 May    2014 2014-05-28        3.7                  16
    ##  9        9 June   2014 2014-06-05        2.52                 14
    ## 10       10 June   2014 2014-06-11        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 10 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, month_num <dbl>,
    ## #   wheel <chr>

``` r
# Professor Trash Wheel
prof_trash <- read_excel(
  path,
  sheet = "Professor Trash Wheel",
  range = cell_limits(c(2,1),c(NA,13)),
  na = c("NA", ".", "")
) %>%
  clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    date = as.Date(date),
    year = year(date),
    month_num = month(date),
    month = month.name[month_num],
    wheel = "Professor Trash Wheel"
  )
prof_trash
```

    ## # A tibble: 132 × 15
    ##    dumpster month     year date       weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <date>           <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02        1.79                 15
    ##  2        2 January   2017 2017-01-30        1.58                 15
    ##  3        3 February  2017 2017-02-26        2.32                 18
    ##  4        4 February  2017 2017-02-26        3.72                 15
    ##  5        5 February  2017 2017-02-28        1.45                 15
    ##  6        6 March     2017 2017-03-30        1.71                 15
    ##  7        7 April     2017 2017-04-01        1.82                 15
    ##  8        8 April     2017 2017-04-20        2.37                 15
    ##  9        9 May       2017 2017-05-10        2.64                 15
    ## 10       10 May       2017 2017-05-26        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, month_num <dbl>, wheel <chr>

``` r
# Gwynnda
gwynnda <- read_excel(
  path,
  sheet = "Gwynns Falls Trash Wheel",
  range = cell_limits(c(2,1), c(NA, 12)),
  na = c("NA", ".", "")
) %>%
  clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    date = as.Date(date),
    year = year(date),
    month_num = month(date),
    month = month.name[month_num],
    wheel = "Gwynns Falls Trash Wheel"
  )
gwynnda
```

    ## # A tibble: 349 × 14
    ##    dumpster month   year date       weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <date>           <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03        0.93                 15
    ##  2        2 July    2021 2021-07-07        2.26                 15
    ##  3        3 July    2021 2021-07-07        1.62                 15
    ##  4        4 July    2021 2021-07-16        1.76                 15
    ##  5        5 July    2021 2021-07-30        1.53                 15
    ##  6        6 August  2021 2021-08-11        2.06                 15
    ##  7        7 August  2021 2021-08-14        1.9                  15
    ##  8        8 August  2021 2021-08-16        2.16                 15
    ##  9        9 August  2021 2021-08-16        2.6                  15
    ## 10       10 August  2021 2021-08-17        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, month_num <dbl>, wheel <chr>

``` r
# Combine
trash_all <- bind_rows(mr_trash, prof_trash, gwynnda) %>%
  arrange(wheel, year, month_num)
trash_all
```

    ## # A tibble: 1,188 × 16
    ##    dumpster month   year date       weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <date>           <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03        0.93                 15
    ##  2        2 July    2021 2021-07-07        2.26                 15
    ##  3        3 July    2021 2021-07-07        1.62                 15
    ##  4        4 July    2021 2021-07-16        1.76                 15
    ##  5        5 July    2021 2021-07-30        1.53                 15
    ##  6        6 August  2021 2021-08-11        2.06                 15
    ##  7        7 August  2021 2021-08-14        1.9                  15
    ##  8        8 August  2021 2021-08-16        2.16                 15
    ##  9        9 August  2021 2021-08-16        2.6                  15
    ## 10       10 August  2021 2021-08-17        3.21                 15
    ## # ℹ 1,178 more rows
    ## # ℹ 10 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, month_num <dbl>,
    ## #   wheel <chr>

### Commenting

The combined Trash Wheel dataset contains 1188 observations spanning
2014 - 2025.

Key variables include `weight_tons`, `volume_cubic_yards`,
`cigarette_butts`, along with date categories (`year`, `month`, `date`).

Across the available data, **Professor Trash Wheel** collected 282.26
tons of trash.

In **June 2022**, **Gwynnda** collected 18,120 cigarette butts.

## Problem 3

### 1. Import and clean the ZIP crosswalk

``` r
zip <- read_csv("./data/Zip Codes.csv", show_col_types = FALSE) %>%
  clean_names() %>%
  mutate(zip = str_pad(as.character(zip_code), width = 5, pad = "0"))
```

### 2. Import and tidy Zillow ZORI

``` r
zori_wide <- read_csv("./data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", show_col_types = FALSE) %>%
  clean_names()

if ("region_name" %in% names(zori_wide)) {
  zori_wide <- zori_wide %>% rename(zip = region_name)
}
zori_wide <- zori_wide %>% mutate(zip = str_pad(as.character(zip), width = 5, side = "left", pad = "0"))
  
  zori <- zori_wide %>%
    pivot_longer(
      cols = starts_with("x20"), 
      names_to = "date_chr",
      values_to = "zori"
    ) %>%
    mutate(
      date = ymd(str_remove(date_chr, "^x") %>% str_replace_all("_", "-")),
      year = year(date),
      month = month(date, label = TRUE, abbr = TRUE)
    ) %>%
    select(zip, date, year, month, zori, city, state, county_name, size_rank)
```

### 3. Merge data and organize

``` r
zori_full <- zori %>%
  left_join(zip, by = "zip") %>%
  mutate(
    county_src = coalesce(county_name, county),
    borough = case_when(
      county_src == "Bronx County" ~ "Bronx",
      county_src == "Kings County" ~ "Brooklyn",
      county_src == "New York County" ~ "Manhatan",
      county_src == "Queens County" ~ "Queens",
      county_src == "Richmond County" ~ "Staten Island",
      TRUE ~ NA_character_
    )
  ) %>%
  select(-county_src) %>%
  relocate(zip, borough, neighborhood, county_name, city, state, .before = date)
```

    ## Warning in left_join(., zip, by = "zip"): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 4757 of `x` matches multiple rows in `y`.
    ## ℹ Row 256 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

``` r
zori_full
```

    ## # A tibble: 17,516 × 17
    ##    zip   borough neighborhood county_name   city    state date        year month
    ##    <chr> <chr>   <chr>        <chr>         <chr>   <chr> <date>     <dbl> <ord>
    ##  1 11368 Queens  West Queens  Queens County New Yo… NY    2015-01-31  2015 Jan  
    ##  2 11368 Queens  West Queens  Queens County New Yo… NY    2015-02-28  2015 Feb  
    ##  3 11368 Queens  West Queens  Queens County New Yo… NY    2015-03-31  2015 Mar  
    ##  4 11368 Queens  West Queens  Queens County New Yo… NY    2015-04-30  2015 Apr  
    ##  5 11368 Queens  West Queens  Queens County New Yo… NY    2015-05-31  2015 May  
    ##  6 11368 Queens  West Queens  Queens County New Yo… NY    2015-06-30  2015 Jun  
    ##  7 11368 Queens  West Queens  Queens County New Yo… NY    2015-07-31  2015 Jul  
    ##  8 11368 Queens  West Queens  Queens County New Yo… NY    2015-08-31  2015 Aug  
    ##  9 11368 Queens  West Queens  Queens County New Yo… NY    2015-09-30  2015 Sep  
    ## 10 11368 Queens  West Queens  Queens County New Yo… NY    2015-10-31  2015 Oct  
    ## # ℹ 17,506 more rows
    ## # ℹ 8 more variables: zori <dbl>, size_rank <dbl>, county <chr>,
    ## #   state_fips <dbl>, county_code <chr>, county_fips <dbl>, zip_code <dbl>,
    ## #   file_date <chr>

### 4. Brief description

- There are 17516 total observations.
- There are 149 unique ZIP codes included.
- There are 43 unique neighborhoods.

### 5. ZIPs in ZIP code dataset but not in Zillow dataset

``` r
zip_only_in_code <- zip %>%
  anti_join(zori_full %>% distinct(zip), by = "zip") %>%
  arrange(zip)
```

### 6. Largest price drop for all ZIPs

``` r
# Compute the Jan 2021 vs Jan 2020 difference per ZIP
jan_diff <- zori_full %>%
  filter(month == "Jan", year %in% c(2020, 2021)) %>%
  select(zip, year, zori) %>%
  pivot_wider(names_from = year, values_from = zori) %>%
  mutate(across(c(`2020`, `2021`), ~as.numeric(as.character(.)))) %>%
  transmute(zip, jan_diff_21_minus_20 = `2021` - `2020`)
```

    ## Warning: Values from `zori` are not uniquely identified; output will contain list-cols.
    ## • Use `values_fn = list` to suppress this warning.
    ## • Use `values_fn = {summary_fun}` to summarise duplicates.
    ## • Use the following dplyr code to identify duplicates.
    ##   {data} |>
    ##   dplyr::summarise(n = dplyr::n(), .by = c(zip, year)) |>
    ##   dplyr::filter(n > 1L)

    ## Warning: There were 2 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `across(c(`2020`, `2021`), ~as.numeric(as.character(.)))`.
    ## Caused by warning:
    ## ! NAs introduced by coercion
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.

``` r
# Add it to zori_full
zori_full <- zori_full %>%
  left_join(jan_diff, by = "zip") %>%
  mutate(jan_diff = as.numeric(jan_diff_21_minus_20))

top10_drop <- zori_full %>%
  distinct(zip, borough, neighborhood, jan_diff) %>%
  arrange(jan_diff) %>%
  slice_head(n = 10)

kable(
  top10_drop,
  digits = 2,
  col.names = c("Zip Code", "Borough", "Neighborhood", "Price Drop"),
  caption = "Top 10 ZIP codes with largest drop in ZORI from Jan 2020 to Jan 2021"
)
```

| Zip Code | Borough  | Neighborhood                  | Price Drop |
|:---------|:---------|:------------------------------|-----------:|
| 10007    | Manhatan | Lower Manhattan               |    -912.60 |
| 10069    | Manhatan | NA                            |    -748.12 |
| 10009    | Manhatan | Lower East Side               |    -714.25 |
| 10016    | Manhatan | Gramercy Park and Murray Hill |    -711.70 |
| 10001    | Manhatan | Chelsea and Clinton           |    -710.45 |
| 10002    | Manhatan | Lower East Side               |    -710.30 |
| 10004    | Manhatan | Lower Manhattan               |    -705.96 |
| 10038    | Manhatan | Lower Manhattan               |    -697.59 |
| 10012    | Manhatan | Greenwich Village and Soho    |    -686.22 |
| 10010    | Manhatan | Gramercy Park and Murray Hill |    -684.93 |

Top 10 ZIP codes with largest drop in ZORI from Jan 2020 to Jan 2021
